spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: rootroot

  jpa:
    show-sql: true
    database: mysql

openweathermap:
  key: 4d16eaf605e8643aec3ac7f317a8af90